# Usage:
# vortex --template ./environments/default.yaml --output temporalenv \
#   --set="namespace=mymongo" \
#   --set="affinitykey=node-type" \
#   --set="affinityselector=mongodb" \
#   --set="storageclass=fast-retain" \
#   --set="image=mongo:4" \
#   --set="storagesize=500Gi" \
#   --set="cpurequest=1" \
#   --set="memoryrequest=200Mi" \
#   --set="cpulimit=2" \
#   --set="memorylimit=500Mi" \
#   --set="rootuser=root" \
#   --set="rootpwd=R0!ot" \
#   --set="replicaset=MyReplSet" \
#   --set="sslmode=allowSSL" \
#   --set="sslenabled=false"

dev: "true"
image: "{{.image}}"
namespace: "{{.namespace}}"
replica: "3"
with_affinity: "true"
pod_affinity_key: "app"
pod_affinity_selector: "mongodb"
node_affinity_key: "{{.affinitykey}}"
node_affinity_selector: "{{.affinityselector}}"
storage_size: "{{.storagesize}}"
storage_class: "{{.storageclass}}" #local-scsi can be selected on GKE with the ./templates/gke-storage applied
resources:
  requests:
    cpu: "{{.cpurequest}}"
    memory: "{{.memoryrequest}}"
  limits:
    cpu: "{{.cpulimit}}"
    memory: "{{.memorylimit}}"
mongodb:
  rootusername: "{{.rootuser}}"
  rootpassword: "{{.rootpwd}}"
  replsetname: "{{.replicaset}}"
  sslmode: "{{.sslmode}}"
mongosidecar:
  sslenabled: "{{.sslenabled}}"
