# Usage:
# vortex --template ./environments/default.yaml --output temporalenv \
#   --set="namespace=mymongo" \
#   --set="nodeaffinitykey=node-type" \
#   --set="nodeaffinityselector=mongodb" \
#   --set="podaffinitykey=app" \
#   --set="podaffinityselector=mongodb" \
#   --set="storageclass=fast-retain" \
#   --set="image=mongo:4" \
#   --set="storagesize=500Gi" \
#   --set="cpurequest=1" \
#   --set="memoryrequest=200Mi" \
#   --set="cpulimit=2" \
#   --set="memorylimit=500Mi" \
#   --set="rootuser=root" \
#   --set="rootpwd=R0!ot" \
#   --set="replicaset=MyReplSet" \
#   --set="sslmode=allowSSL" \
#   --set="sslenabled=false" \
#   --set="with_gcs_backups=true" \
#   --set="gcs_bucket=mongodb-gcs-backups"

dev: "true"
image: "{{.image}}"
namespace: "{{.namespace}}"
replica: "3"
with_affinity: "true"
# These wll not apply  -----------------
pod_affinity_key: "{{.podaffinitykey}}"
pod_affinity_selector: "{{.podaffinityselector}}"
node_affinity_key: "{{.nodeaffinitykey}}"
node_affinity_selector: "{{.nodeaffinityselector}}"
# --------------------------------------
storage_size: "{{.storagesize}}"
storage_class: "{{.storageclass}}" #local-scsi can be selected on GKE with the ./templates/gke-storage applied
with_gcs_backups: "{{.with_gcs_backups}}"
gcsfuse:
  storage_bucket: "{{.gcs_bucket}}"
resources:
  requests:
    cpu: "{{.cpurequest}}"
    memory: "{{.memoryrequest}}"
  limits:
    cpu: "{{.cpulimit}}"
    memory: "{{.memorylimit}}"
mongodb:
  rootusername: "{{.rootuser}}"
  rootpassword: "{{.rootpwd}}"
  replsetname: "{{.replicaset}}"
  sslmode: "{{.sslmode}}"
mongosidecar:
  sslenabled: "{{.sslenabled}}"
