dev: "true"
image: "mongo:3.6"
namespace: "mongodb"
replica: "3"
# with_affinity: true
# node_affinity_key: "node-type"
# node_affinity_selector: "mongodb"
# pod_anti_affinity_key: "app"
# pod_anti_affinity_selector: "mongodb"
storage_size: "1Gi"
storage_class: "fast-retain"
resources:
  requests:
    cpu: "0.2m"
    memory: "200Mi"
  limits:
    cpu: ""
    memory: ""
mongodb:
  rootusername: "root"
  rootpassword: "root"
  replsetname: "MainRepSet"
  sslmode: "preferSSL"
mongosidecar:
  sslenabled: "true"
