dev: "true"
image: "mongo"
namespace: "mongodb"
replica: "3"
affinity_key: "app"
affinity_selector: "mongodb"
storage_size: "1Gi"
storage_class: "fast-retain"
resources:
  requests:
    cpu: "0.2m"
    memory: "200Mi"
  limits:
    cpu: ""
    memory: ""
mongodb:
  rootusername: "root"
  rootpassword: "root"
  replsetname: "MainRepSet"
  sslmode: "preferSSL"
mongosidecar:
  sslenabled: "true"
