image: "mongo:3.6"
namespace: "mongodb"
replica: "3"
with_affinity: "false"
# These wll not apply  -----------------
pod_affinity_key: "app"
pod_affinity_selector: "mongodb"
node_affinity_key: "node-type"
node_affinity_selector: "mongodb"
# --------------------------------------
storage_size: "1Gi"
storage_class: "fast-retain" #local-scsi can be selected on GKE with the ./templates/gke-storage applied
resources:
  requests:
    cpu: "0.2m"
    memory: "200Mi"
  limits:
    cpu: ""
    memory: ""
mongodb:
  rootusername: "root"
  rootpassword: "root"
  replsetname: "MainRepSet"
  sslmode: "preferSSL"
mongosidecar:
  sslenabled: "true"
