image: "mongo:3-stretch"
namespace: "mongodb"
replica: "3"
with_affinity: "true"
pod_affinity_key: "app"
pod_affinity_selector: "mongodb"
node_affinity_key: "node-type"
node_affinity_selector: "mongodb"
with_gcs_backups: "true"
gcsfuse:
  storage_bucket: mongodb-gcs-backups
storage_size: "250Gi"
storage_class: "local-scsi" #local-scsi can be selected on GKE with the ./templates/gke-storage applied
resources:
  requests:
    cpu: "2"
    memory: "1000Mi"
  limits:
    cpu: "3"
    memory: "30000Mi"
mongodb:
  rootusername: "root"
  rootpassword: "root"
  replsetname: "MainRepSet"
  sslmode: "preferSSL"
mongosidecar:
  sslenabled: "true"
