# Usage:
# vortex --template ./environments/default.yaml --output temporalenv \
#   --set="namespace=mymongo" \
#   --set="affinitykey=node-type" \
#   --set="affinityselector=mongodb" \
#   --set="storageclass=fast-retain" \
#   --set="image=mongo:4" \
#   --set="storagesize=500Gi" \
#   --set="cpurequest=1" \
#   --set="memoryrequest=200Mi" \
#   --set="cpulimit=2" \
#   --set="memorylimit=500Mi" \
#   --set="rootuser=root" \
#   --set="rootpwd=R0!ot" \
#   --set="replicaset=MyReplSet" \
#   --set="sslmode=allowSSL" \
#   --set="sslenabled=false"

dev: "true"
image: "mongo:3.6-xenial"
namespace: "mongodb"
replica: "3"
with_affinity: true
node_affinity_selector: "node-type"
node_affinity_key: "mongodb"
pod_anti_affinity_selector: "app"
pod_anti_affinity_key: "mongodb"
storage_size: "500Gi"
storage_class: "fast-retain"
resources:
  requests:
    cpu: "2"
    memory: "500Mi"
  limits:
    cpu: "4"
    memory: "30000Mi"
mongodb:
  rootusername: "root"
  rootpassword: "root"
  replsetname: "MainRepSet"
  sslmode: "allowSSL"
mongosidecar:
  sslenabled: "false"
