---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
    component: mongodb
    role: services
  annotations:
      cloud.google.com/load-balancer-type: "Internal"

spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - name: mongo
    port: 27017
  selector:
    app: mongodb
    component: mongodb
    role: services
