---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
    component: mongodb
    role: services
spec:
  clusterIP: None
  ports:
  - name: mongo
    port: 27017
  selector:
    app: mongodb
    component: mongodb
    role: services
