---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod
  namespace: mongodb
  labels:
    app: mongodb
    component: mongodb
    role: services
spec:
  serviceName: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
        component: mongodb
        role: services
    spec:
      serviceAccount: kubernetes-mongodb-service-account
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: copy-ro-scripts
        image: busybox
        command: ['sh', '-c', 'cp /tmp/rs-key /mongotemp/rs-key && chmod 0400 /mongotemp/rs-key && chown 999:999 /mongotemp/rs-key']
        volumeMounts:
        - name: mongodb-rs-key
          mountPath: /tmp/rs-key
          subPath: rs-key
        - name: tempvol
          mountPath: /mongotemp
      containers:
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: "app=mongodb,role=services,component=mongodb"
        - name: MONGODB_USERNAME
          value: "root"
        - name: MONGODB_PASSWORD
          value: "root"
        - name: KUBERNETES_MONGO_SERVICE_NAME
          value: "mongodb"
        - name: MONGO_SSL_ENABLED
          value: 'true'
        - name: MONGO_SSL_ALLOW_INVALID_CERTIFICATES
          value: "true"
        - name: MONGO_SSL_ALLOW_INVALID_HOSTNAMES
          value: "true"
        - name: MONGODB_DATABASE
          value: "admin"
      - name: mongod
        image: mongo
        args:
          - "mongod"
          - "--wiredTigerCacheSizeGB"
          - "1.5"
          - "--bind_ip"
          - "0.0.0.0"
          - "--replSet"
          - "MainRepSet"
          - "--smallfiles"
          - "--noprealloc"
          - "--auth"
          - "--sslMode"
          - "preferSSL"
          - "--sslPEMKeyFile"
          - "/etc/mongodb-secret/mongodb.pem"
          - "--sslAllowConnectionsWithoutCertificates"
          - "--sslAllowInvalidCertificates"
          - "--sslAllowInvalidHostnames"
          - "--config"
          - "/etc/mongodb-config/mongodb.conf"
        resources:
          requests:
            memory: "200Mi"
            cpu: "0.2m"
          limits:
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "root"
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - name: mongodb-secret
          mountPath: /etc/mongodb-secret/mongodb.pem
          subPath: mongodb.pem
        - name: mongodb-config
          mountPath: /etc/mongodb-config/mongodb.conf
          subPath: mongodb.conf
        - name: tempvol
          mountPath: /mongotemp
        - name: data
          mountPath: /data/db
      volumes:
      - name: tempvol
        emptyDir: {}
      - name: mongodb-secret
        secret:
          secretName: mongodb-secret
      - name: mongodb-rs-key
        secret:
          secretName: mongodb-rs-key
      - name: mongodb-config
        configMap:
          name: mongodb-config
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: volume
        component: mongodb
        role: services
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: fast-retain
      resources:
        requests:
          storage: 1Gi
