apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-mongodb-service-account
  namespace: mongodb

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-mongodb-service-account-binding
subjects:
  - kind: ServiceAccount
    name: kubernetes-mongodb-service-account
    namespace: mongodb
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""
