---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
  namespace: {{.namespace}}
  labels:
    app: mongodb
    component: mongodb
    role: services
spec:
  selector:
    matchLabels:
      app: mongodb
      component: mongodb
      role: services
  serviceName: mongodb
  replicas: {{ .replica }}
  template:
    metadata:
      labels:
        app: mongodb
        component: mongodb
        role: services
    spec:
      serviceAccount: kubernetes-mongodb-service-account
{{- if not .dev }}
{{- if .affinity_key }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: {{.affinity_key}}
                  operator: In
                  values:
                  - {{.affinity_selector}}
              topologyKey: kubernetes.io/hostname
{{- end }}
{{- end }}
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: copy-ro-scripts
        image: busybox
        command: ['sh', '-c', 'cp /tmp/rs-key /mongotemp/rs-key && chmod 0400 /mongotemp/rs-key && chown 999:999 /mongotemp/rs-key']
        volumeMounts:
        - name: mongodb-rs-key
          mountPath: /tmp/rs-key
          subPath: rs-key
        - name: tempvol
          mountPath: /mongotemp
      containers:
      - name: mongo-sidecar
        image: morphy/k8s-mongo-sidecar:latest
        env:
          #https://github.com/morphy2k/k8s-mongo-sidecar
        - name: KUBERNETES_POD_LABELS
          value: "app=mongodb,role=services,component=mongodb"
        - name: KUBERNETES_SERVICE_NAME
          value: "mongodb"
        - name: KUBERNETES_NAMESPACE
          value: "{{.namespace}}"
        - name: MONGO_USERNAME
          value: "{{.mongodb.rootusername}}"
        - name: MONGO_PASSWORD
          value: "{{.mongodb.rootpassword}}"
        - name: MONGO_SSL_ENABLED
          value: "{{.mongosidecar.sslenabled}}"
        - name: MONGO_SSL_ALLOW_INVALID_CERTIFICATES
          value: "true"
        - name: MONGO_SSL_ALLOW_INVALID_HOSTNAMES
          value: "true"
        - name: MONGO_SSL_CERT
          value: "/etc/mongodb-secret/mongodb.pem"
        - name: MONGO_SSL_KEY
          value: "/mongotemp/rs-key"
        volumeMounts:
        - name: mongodb-secret
          mountPath: /etc/mongodb-secret/mongodb.pem
          subPath: mongodb.pem
        - name: mongodb-rs-key
          mountPath: /etc/mongodb-secret/rs-key
          subPath: rs-key

      - name: mongod
        image: {{.image}}
        args:
          - "mongod"
          - "--wiredTigerCacheSizeGB"
          - "1.5"
          - "--smallfiles"
          - "--noprealloc"
          - "--auth"
          - "--config"
          - "/etc/mongodb-config/mongodb.conf"
        resources:
          requests:
{{- if ne .resources.requests.memory "" }}
            memory: "{{ .resources.requests.memory }}"
{{- end }}
{{- if ne .resources.requests.cpu "" }}
            cpu: "{{ .resources.requests.cpu }}"The command '/bin/sh -c GO111MODULE=on go build -ldflags="-s -w -X 'main.version=$(cat VERSION)' -X 'main.revision=$(git rev-parse --short HEAD)' -X 'main.buildtime=$(date -u +%Y-%m-%d.%H:%M:%S)'" -o /gravitywell &&     rm -rf ${GOPATH}' returned a non-zero code: 1
{{- end }}
          limits:
{{- if ne .resources.limits.memory "" }}
            memory: "{{ .resources.limits.memory }}"
{{- end }}
{{- if ne .resources.limits.cpu "" }}
            cpu: "{{ .resources.limits.cpu }}"
{{- end }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "{{.mongodb.rootusername}}"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "{{.mongodb.rootpassword}}"
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - name: mongodb-secret
          mountPath: /etc/mongodb-secret/mongodb.pem
          subPath: mongodb.pem
        - name: mongodb-rs-key
          mountPath: /etc/mongodb-secret/rs-key
          subPath: rs-key
        - name: mongodb-config
          mountPath: /etc/mongodb-config/mongodb.conf
          subPath: mongodb.conf
        - name: tempvol
          mountPath: /mongotemp
        - name: data
          mountPath: /data/db
      volumes:
      - name: tempvol
        emptyDir: {}
      - name: mongodb-secret
        secret:
          secretName: mongodb-secret
      - name: mongodb-rs-key
        secret:
          secretName: mongodb-rs-key
      - name: mongodb-config
        configMap:
          name: mongodb-config
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: volume
        component: mongodb
        role: services
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: {{.storage_class}}
      resources:
        requests:
          storage: {{.storage_size}}
