apiVersion: batch/v1
kind: Job
metadata:
  name: mongojob
spec:
  template:
    spec:
      containers:
      - name: mongo-job
        image: {{.image}}
        command:
          - /bin/sh
          - -c
          - mongo --host mongod-0.mongodb.mongodb.svc.cluster.local:27017 --authenticationDatabase admin --username {{.mongodb.rootusername}} --password {{.mongodb.rootpassword}} --eval "rs.status()"
      restartPolicy: Never
  backoffLimit: 4
