apiVersion: v1
kind: Pod
metadata:
  name: mongopod
spec:
  containers:
  - name: mongo-pod
    image: {{.image}}
    command:
      - /bin/sh
      - -c
      - "sleep 6000"
#
# Use a simple container like this with kubectl cp to then run
# mongorestore --host mongod-0.mongodb.mongodb.svc.cluster.local:27017 -\
# -authenticationDatabase admin --username <username> --password <password> --db seed --drop --gzip --archive=seed.agz
